# Generated by Django 6.0.7 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        ("main", "0007_cooperationstep"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_active_appointment_start",
        ),
        migrations.AddField(
            model_name="appointment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Opłacono"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Kwota płatności"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_currency",
            field=models.CharField(default="PLN", max_length=3, verbose_name="Waluta"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Blokada terminu wygasa"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_status",
            field=models.CharField(choices=[("not_required", "Nie dotyczy"), ("pending", "Oczekuje na płatność"), ("paid", "Opłacona"), ("failed", "Nieudana / wygasła"), ("refunded", "Zwrócona")], default="not_required", max_length=20, verbose_name="Status płatności"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Identyfikator sesji Stripe"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, verbose_name="Identyfikator płatności Stripe"),
        ),
        migrations.AddField(
            model_name="bookingsettings",
            name="payment_hold_minutes",
            field=models.PositiveIntegerField(default=30, help_text="Stripe Checkout wymaga co najmniej 30 minut.", verbose_name="Czas na opłacenie rezerwacji (minuty)"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(choices=[("pending_payment", "Oczekuje na płatność"), ("pending", "Oczekuje"), ("confirmed", "Potwierdzona"), ("completed", "Odbyta"), ("cancelled", "Anulowana"), ("no_show", "Nieobecność")], default="pending", max_length=20, verbose_name="Status"),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(condition=models.Q(("status__in", ["pending_payment", "pending", "confirmed"])), fields=("start_at",), name="unique_active_appointment_start"),
        ),
    ]
