# Generated by Django 6.0.7 on 2026-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_stripe_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Anulowanie e-mail wysłano'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Potwierdzenie e-mail wysłano'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='previous_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Poprzedni termin wizyty'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Przypomnienie e-mail wysłano'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zmianę terminu e-mail wysłano'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termin zmieniono'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='cancellation_notice_hours',
            field=models.PositiveIntegerField(default=24, verbose_name='Najpóźniejsze anulowanie / przełożenie (godziny przed wizytą)'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Pozostaw puste, jeśli powiadomienia mają trafiać tylko do pacjenta.', max_length=254, verbose_name='E-mail Moniki do powiadomień o rezerwacjach'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='reminder_hours_before',
            field=models.PositiveIntegerField(default=24, verbose_name='Wyślij przypomnienie przed wizytą (godziny)'),
        ),
    ]
