# Generated by Django 6.0.7 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("booking", "0003_appointment_cancellation_email_sent_at_and_more")]

    operations = [
        migrations.AlterField(model_name="appointment", name="consent_privacy", field=models.BooleanField(default=False, verbose_name="Potwierdzenie zapoznania się z polityką prywatności")),
        migrations.AddField(model_name="appointment", name="privacy_acknowledged_at", field=models.DateTimeField(blank=True, null=True, verbose_name="Data potwierdzenia polityki prywatności")),
        migrations.AddField(model_name="appointment", name="privacy_snapshot", field=models.TextField(blank=True, verbose_name="Treść polityki prywatności przy rezerwacji")),
        migrations.AddField(model_name="appointment", name="privacy_version", field=models.CharField(blank=True, max_length=30, verbose_name="Wersja polityki prywatności")),
        migrations.AddField(model_name="appointment", name="terms_accepted", field=models.BooleanField(default=False, verbose_name="Akceptacja regulaminu")),
        migrations.AddField(model_name="appointment", name="terms_accepted_at", field=models.DateTimeField(blank=True, null=True, verbose_name="Data akceptacji regulaminu")),
        migrations.AddField(model_name="appointment", name="terms_snapshot", field=models.TextField(blank=True, verbose_name="Treść zaakceptowanego regulaminu")),
        migrations.AddField(model_name="appointment", name="terms_version", field=models.CharField(blank=True, max_length=30, verbose_name="Zaakceptowana wersja regulaminu")),
    ]
