# Generated by Django 6.0.7 on 2026-08-30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0007_cooperationstep"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedTime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="Data")),
                ("start_time", models.TimeField(blank=True, help_text="Pozostaw obie godziny puste, aby zablokować cały dzień.", null=True, verbose_name="Od godziny")),
                ("end_time", models.TimeField(blank=True, null=True, verbose_name="Do godziny")),
                ("reason", models.CharField(blank=True, max_length=200, verbose_name="Powód / notatka")),
            ],
            options={
                "verbose_name": "Zablokowany termin",
                "verbose_name_plural": "Zablokowane terminy i dni wolne",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="BookingSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slot_interval_minutes", models.PositiveIntegerField(default=15, help_text="Na przykład 15 pozwala wyświetlić terminy 09:00, 09:15, 09:30 itd.", verbose_name="Odstęp między możliwymi godzinami rozpoczęcia")),
                ("buffer_minutes", models.PositiveIntegerField(default=15, verbose_name="Przerwa między wizytami (minuty)")),
                ("minimum_notice_hours", models.PositiveIntegerField(default=24, verbose_name="Minimalne wyprzedzenie rezerwacji (godziny)")),
                ("booking_window_days", models.PositiveIntegerField(default=90, verbose_name="Maksymalny okres rezerwacji (dni)")),
            ],
            options={
                "verbose_name": "Ustawienia rezerwacji",
                "verbose_name_plural": "Ustawienia rezerwacji",
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weekday", models.PositiveSmallIntegerField(choices=[(0, "Poniedziałek"), (1, "Wtorek"), (2, "Środa"), (3, "Czwartek"), (4, "Piątek"), (5, "Sobota"), (6, "Niedziela")], verbose_name="Dzień tygodnia")),
                ("start_time", models.TimeField(verbose_name="Od godziny")),
                ("end_time", models.TimeField(verbose_name="Do godziny")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktywne")),
            ],
            options={
                "verbose_name": "Godziny pracy",
                "verbose_name_plural": "Godziny pracy",
                "ordering": ["weekday", "start_time"],
                "constraints": [
                    models.UniqueConstraint(fields=("weekday", "start_time", "end_time"), name="unique_working_hours_period"),
                    models.CheckConstraint(condition=models.Q(("end_time__gt", models.F("start_time"))), name="working_hours_end_after_start"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("start_at", models.DateTimeField(verbose_name="Początek wizyty")),
                ("end_at", models.DateTimeField(verbose_name="Koniec wizyty")),
                ("visit_type", models.CharField(choices=[("online", "Online"), ("in_person", "Stacjonarnie")], default="online", max_length=20, verbose_name="Forma wizyty")),
                ("first_name", models.CharField(max_length=100, verbose_name="Imię")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nazwisko")),
                ("email", models.EmailField(max_length=254, verbose_name="Adres e-mail")),
                ("phone", models.CharField(max_length=30, verbose_name="Numer telefonu")),
                ("notes", models.TextField(blank=True, help_text="Nie wpisuj tutaj szczegółowych informacji medycznych.", verbose_name="Krótka wiadomość")),
                ("consent_privacy", models.BooleanField(default=False, verbose_name="Zgoda na przetwarzanie danych w celu obsługi rezerwacji")),
                ("status", models.CharField(choices=[("pending", "Oczekuje"), ("confirmed", "Potwierdzona"), ("completed", "Odbyta"), ("cancelled", "Anulowana"), ("no_show", "Nieobecność")], default="pending", max_length=20, verbose_name="Status")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano")),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="appointments", to="main.service", verbose_name="Usługa")),
            ],
            options={
                "verbose_name": "Wizyta",
                "verbose_name_plural": "Wizyty",
                "ordering": ["start_at"],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("end_at__gt", models.F("start_at"))), name="appointment_end_after_start"),
                    models.UniqueConstraint(condition=models.Q(("status__in", ["pending", "confirmed"])), fields=("start_at",), name="unique_active_appointment_start"),
                ],
            },
        ),
    ]
