# Generated by Django 6.0.7 on 2026-07-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='O mnie', max_length=150, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Strona O mnie',
                'verbose_name_plural': 'Strona O mnie',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa specjalizacji')),
            ],
            options={
                'verbose_name': 'Specjalizacja',
                'verbose_name_plural': 'Specjalizacje',
                'ordering': ['name'],
            },
        ),
    ]
