# Generated by Django 6.0.7 on 2026-07-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Zdjęcie'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Krótki tekst wyświetlany pod głównym tytułem.', max_length=250, verbose_name='Krótki nagłówek'),
        ),
    ]
