# Generated by Django 6.0.7 on 2026-08-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutpage_photo_aboutpage_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['order'], 'verbose_name': 'Specjalizacja', 'verbose_name_plural': 'Specjalizacje'},
        ),
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, verbose_name='Krótki opis'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Wyświetlaj na stronie'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Kolejność'),
        ),
    ]
