# Generated by Django 6.0.7 on 2026-08-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_specialization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Dietetyka dopasowana do Ciebie', max_length=150, verbose_name='Mały nagłówek Hero')),
                ('hero_title', models.CharField(default='Zdrowie zaczyna się od dobrych wyborów', max_length=250, verbose_name='Główny nagłówek Hero')),
                ('hero_description', models.TextField(default='Pomagam odzyskać równowagę między zdrowiem, samopoczuciem i codziennym stylem życia.', verbose_name='Opis Hero')),
                ('hero_photo', models.ImageField(blank=True, null=True, upload_to='home/hero/', verbose_name='Zdjęcie Hero')),
            ],
            options={
                'verbose_name': 'Strona główna',
                'verbose_name_plural': 'Strona główna',
            },
        ),
    ]
