# Generated by Django 6.0.7 on 2026-08-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo')),
                ('site_name', models.CharField(default='Dietetyk Monika', max_length=150, verbose_name='Nazwa strony')),
            ],
            options={
                'verbose_name': 'Ustawienia strony',
                'verbose_name_plural': 'Ustawienia strony',
            },
        ),
    ]
