# Generated by Django 6.0.7 on 2026-08-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa usługi')),
                ('short_description', models.TextField(blank=True, help_text='Krótki opis widoczny na karcie oferty.', verbose_name='Krótki opis')),
                ('details', models.TextField(blank=True, help_text='Pełniejszy opis usługi. Wykorzystamy go później na stronie oferty.', verbose_name='Szczegóły usługi')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Pozostaw puste, jeśli cena nie ma być wyświetlana.', max_digits=8, null=True, verbose_name='Cena')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Czas trwania w minutach')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Zdjęcie / grafika usługi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_active', models.BooleanField(default=True, verbose_name='Wyświetlaj na stronie')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Wyróżniona usługa')),
            ],
            options={
                'verbose_name': 'Usługa',
                'verbose_name_plural': 'Usługi',
                'ordering': ['order'],
            },
        ),
    ]
