# Generated by Django 6.0.7 on 2026-08-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nazwa etapu')),
                ('description', models.TextField(verbose_name='Opis etapu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_active', models.BooleanField(default=True, verbose_name='Wyświetlaj na stronie')),
            ],
            options={
                'verbose_name': 'Etap współpracy',
                'verbose_name_plural': 'Etapy współpracy',
                'ordering': ['order'],
            },
        ),
    ]
