# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_cooperationstep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="description",
            field=models.TextField(
                help_text=(
                    "Aby wyróżnić fragment na stronie, otocz go podwójnymi gwiazdkami. "
                    "Przykład: **odŻYWIENIE**."
                ),
                verbose_name="Opis",
            ),
        ),
    ]
