# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_aboutpage_description_accent_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_description",
            field=models.TextField(
                default="Pomagam odzyskać równowagę między zdrowiem, samopoczuciem i codziennym stylem życia.",
                help_text=(
                    "Aby wyróżnić fragment na stronie, otocz go podwójnymi gwiazdkami. "
                    "Przykład: **odŻYWIENIE**."
                ),
                verbose_name="Opis Hero",
            ),
        ),
    ]
