# Generated by Codex on 2026-09-10

from django.db import migrations, models


def seed_help_steps(apps, schema_editor):
    CooperationStep = apps.get_model("main", "CooperationStep")
    if CooperationStep.objects.exists():
        return

    CooperationStep.objects.bulk_create(
        [
            CooperationStep(
                order=1,
                title="Poznaję Twój punkt wyjścia",
                description=(
                    "Przed konsultacją wnikliwie zapoznaję się z Twoją ankietą zdrowotną, "
                    "wynikami badań laboratoryjnych oraz informacjami zebranymi podczas spotkania. "
                    "Wspólnie określamy Twoje cele i priorytety współpracy."
                ),
            ),
            CooperationStep(
                order=2,
                title="Tworzę plan działania dopasowany do Twoich potrzeb",
                description=(
                    "Zebrane informacje analizuję całościowo, szukając istotnych zależności. "
                    "Opracowuję zalecenia dotyczące żywienia, stylu życia i suplementacji, "
                    "uwzględniając Twoje cele oraz realia codzienności."
                ),
            ),
            CooperationStep(
                order=3,
                title="Towarzyszę Ci w procesie zmiany",
                description=(
                    "Pozostajemy w kontakcie. Podczas kolejnych konsultacji omawiamy efekty "
                    "i trudności, a gdy potrzeba, modyfikuję zalecenia. Wypracowujemy model "
                    "żywienia, który sprawdza się w codziennym życiu."
                ),
            ),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_homepage_hero_description_accent_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="help_description",
            field=models.TextField(
                default=(
                    "Każdy organizm opowiada własną historię. Chcę się w nią uważnie wsłuchać, "
                    "aby lepiej zrozumieć płynące z niego sygnały i wyznaczyć kierunek działania, "
                    "który pozwoli odnaleźć klucz do Twojego sukcesu — niezależnie czy jest nim "
                    "redukcja wagi, osiągnięcie konkretnych celów zdrowotnych, poprawa "
                    "samopoczucia czy realizacja kilku założeń jednocześnie. W tym celu łączę "
                    "wiedzę z zakresu dietetyki klinicznej z elementami fitoterapii, technik "
                    "oddechowych i aromaterapii."
                ),
                help_text=(
                    "Aby wyróżnić fragment na stronie, otocz go podwójnymi gwiazdkami. "
                    "Przykład: **odŻYWIENIE**."
                ),
                verbose_name="Opis sekcji Jak pomagam",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="help_eyebrow",
            field=models.CharField(
                default="Jak pomagam",
                max_length=150,
                verbose_name="Mały nagłówek sekcji Jak pomagam",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="help_specializations_title",
            field=models.CharField(
                default="Obszary, w których mogę Ci pomóc",
                max_length=250,
                verbose_name="Nagłówek specjalizacji",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="help_title",
            field=models.CharField(
                default="Od poznania Twojej historii do stworzenia planu, który działa",
                max_length=250,
                verbose_name="Główny nagłówek sekcji Jak pomagam",
            ),
        ),
        migrations.AlterField(
            model_name="cooperationstep",
            name="description",
            field=models.TextField(
                help_text="Opis etapu widoczny pod jego tytułem na stronie głównej.",
                verbose_name="Opis etapu",
            ),
        ),
        migrations.AlterField(
            model_name="cooperationstep",
            name="title",
            field=models.CharField(
                help_text="Tytuł jednego z trzech etapów w sekcji Jak pomagam.",
                max_length=150,
                verbose_name="Nazwa etapu",
            ),
        ),
        migrations.AlterModelOptions(
            name="cooperationstep",
            options={
                "ordering": ["order"],
                "verbose_name": "Etap „Jak pomagam”",
                "verbose_name_plural": "Etapy „Jak pomagam”",
            },
        ),
        migrations.RunPython(seed_help_steps, migrations.RunPython.noop),
    ]
