# Generated by Codex on 2026-09-10

from django.db import migrations, models


OLD_HELP_EYEBROW = "Jak pomagam"
OLD_HELP_TITLE = "Od poznania Twojej historii do stworzenia planu, który działa"

OLD_STEP_DESCRIPTIONS = {
    "Poznaję Twój punkt wyjścia": (
        "Przed konsultacją wnikliwie zapoznaję się z Twoją ankietą zdrowotną, "
        "wynikami badań laboratoryjnych oraz informacjami zebranymi podczas spotkania. "
        "Wspólnie określamy Twoje cele i priorytety współpracy."
    ),
    "Tworzę plan działania dopasowany do Twoich potrzeb": (
        "Zebrane informacje analizuję całościowo, szukając istotnych zależności. "
        "Opracowuję zalecenia dotyczące żywienia, stylu życia i suplementacji, "
        "uwzględniając Twoje cele oraz realia codzienności."
    ),
    "Towarzyszę Ci w procesie zmiany": (
        "Pozostajemy w kontakcie. Podczas kolejnych konsultacji omawiamy efekty "
        "i trudności, a gdy potrzeba, modyfikuję zalecenia. Wypracowujemy model "
        "żywienia, który sprawdza się w codziennym życiu."
    ),
}

ISSUE_STEP_DESCRIPTIONS = {
    "Poznaję Twój punkt wyjścia": (
        "Przed konsultacją wnikliwie zapoznaję się z Twoją ankietą zdrowotną, którą "
        "otrzymujesz po umówieniu wizyty. Jej uzupełnieniem są wyniki badań laboratoryjnych "
        "oraz informacje zebrane podczas naszego spotkania. Na tej podstawie wspólnie "
        "określamy Twoje cele i priorytety współpracy."
    ),
    "Tworzę plan działania dopasowany do Twoich potrzeb": (
        "Zebrane informacje analizuję całościowo, szukając istotnych zależności. Następnie "
        "opracowuję zalecenia dotyczące żywienia i stylu życia, a także suplementacji "
        "nastawionej na uzupełnienie indywidualnych niedoborów i realne wsparcie Twojego "
        "organizmu. Uwzględniam przy tym ustalone cele oraz realia codzienności."
    ),
    "Towarzyszę Ci w procesie zmiany": (
        "Pozostajemy w kontakcie. Podczas kolejnych konsultacji omawiamy efekty i pojawiające "
        "się trudności, a w razie potrzeby modyfikuję zalecenia. Wspólnie wypracowujemy model "
        "żywienia, który sprawdza się w codziennym życiu i nie smakuje jak kara."
    ),
}


def adopt_editorial_defaults(apps, schema_editor):
    HomePage = apps.get_model("main", "HomePage")
    CooperationStep = apps.get_model("main", "CooperationStep")

    for page in HomePage.objects.all():
        update_fields = []

        if page.help_eyebrow == OLD_HELP_EYEBROW:
            page.help_eyebrow = "Indywidualne podejście"
            update_fields.append("help_eyebrow")

        if page.help_title == OLD_HELP_TITLE:
            page.help_title = "Jak pomagam?"
            update_fields.append("help_title")

        if update_fields:
            page.save(update_fields=update_fields)

    for title, old_description in OLD_STEP_DESCRIPTIONS.items():
        CooperationStep.objects.filter(
            title=title,
            description=old_description,
        ).update(description=ISSUE_STEP_DESCRIPTIONS[title])


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_homepage_help_section_and_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="help_lead",
            field=models.CharField(
                default="Od poznania Twojej historii do stworzenia planu, który działa",
                help_text="Tekst widoczny pod dużym nagłówkiem po lewej stronie sekcji.",
                max_length=250,
                verbose_name="Krótki wstęp sekcji Jak pomagam",
            ),
        ),
        migrations.AddField(
            model_name="cooperationstep",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text=(
                    "Poziome zdjęcie po prawej stronie etapu. Najlepiej w proporcji około 2:1."
                ),
                null=True,
                upload_to="help_steps/",
                verbose_name="Zdjęcie etapu",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="help_eyebrow",
            field=models.CharField(
                default="Indywidualne podejście",
                max_length=150,
                verbose_name="Nadtytuł sekcji Jak pomagam",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="help_title",
            field=models.CharField(
                default="Jak pomagam?",
                max_length=250,
                verbose_name="Główny nagłówek sekcji Jak pomagam",
            ),
        ),
        migrations.RunPython(adopt_editorial_defaults, migrations.RunPython.noop),
    ]
