# Generated by Django 6.0.7 on 2026-09-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_editorial_help_layout_and_step_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Np. „Anna K.” — dokładnie tak, jak pacjent zgodził się to opublikować.', max_length=150, verbose_name='Imię pacjenta / inicjały')),
                ('content', models.TextField(verbose_name='Treść opinii')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Ocena (1-5)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Zdjęcie pacjenta')),
                ('consent_confirmed', models.BooleanField(default=False, help_text='Zaznacz dopiero po uzyskaniu wyraźnej zgody pacjenta. Opinia nie pojawi się na stronie bez tego.', verbose_name='Pacjent wyraził zgodę na publikację')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('is_active', models.BooleanField(default=True, verbose_name='Wyświetlaj na stronie')),
            ],
            options={
                'verbose_name': 'Opinia pacjenta',
                'verbose_name_plural': 'Opinie pacjentów',
                'ordering': ['order'],
            },
        ),
    ]
