# Generated by Django 6.0.7 on 2026-09-10 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 10, 8, 37, 29, 163995, tzinfo=datetime.timezone.utc), verbose_name='Data zgłoszenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje na moderację'), ('approved', 'Zaakceptowana'), ('rejected', 'Odrzucona')], default='pending', max_length=10, verbose_name='Status moderacji'),
        ),
    ]
