# Generated by Django 6.0.7 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_testimonial_created_at_testimonial_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="newsletter_button_label",
            field=models.CharField(
                default="Zapisz się na newsletter",
                max_length=100,
                verbose_name="Tekst przycisku Newsletter",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="newsletter_description",
            field=models.TextField(
                default=(
                    "Zapisz się, aby otrzymywać praktyczne wskazówki żywieniowe, "
                    "inspiracje i informacje o nowych materiałach."
                ),
                verbose_name="Opis sekcji Newsletter",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="newsletter_eyebrow",
            field=models.CharField(
                default="Newsletter",
                max_length=100,
                verbose_name="Nadtytuł sekcji Newsletter",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="newsletter_title",
            field=models.CharField(
                default="Zdrowa wiedza prosto na Twoją skrzynkę",
                max_length=250,
                verbose_name="Nagłówek sekcji Newsletter",
            ),
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Imię")),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="Adres e-mail",
                    ),
                ),
                (
                    "consent_confirmed",
                    models.BooleanField(
                        default=False,
                        verbose_name="Zgoda marketingowa",
                    ),
                ),
                (
                    "consent_text",
                    models.TextField(
                        help_text="Treść zgody zapisana w chwili zapisu do newslettera.",
                        verbose_name="Treść udzielonej zgody",
                    ),
                ),
                (
                    "consented_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Data udzielenia zgody",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        verbose_name="Aktywny zapis",
                    ),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Data rezygnacji",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zapis do newslettera",
                "verbose_name_plural": "Zapisy do newslettera",
                "ordering": ["-consented_at"],
            },
        ),
    ]
