# Generated by Django 6.0.7 on 2026-09-23

import datetime

from django.db import migrations, models


TERMS_CONTENT = "REGULAMIN ŚWIADCZENIA USŁUG DROGĄ ELEKTRONICZNĄ I REZERWACJI KONSULTACJI\n\n1. USŁUGODAWCA\n\nUsługodawcą jest {{BUSINESS_NAME}}, prowadzona przez {{OWNER_NAME}}, adres: {{ADDRESS}}, NIP: {{TAX_ID}}.\nKontakt: {{EMAIL}}, {{PHONE}}.\n\n2. ZAKRES REGULAMINU\n\nRegulamin określa zasady korzystania ze strony, składania rezerwacji, dokonywania płatności online oraz realizacji konsultacji dietetycznych online i stacjonarnych. Przed płatną rezerwacją Klient ma możliwość zapisania Regulaminu i potwierdza jego akceptację.\n\n3. WYMAGANIA TECHNICZNE\n\nDo korzystania ze strony wymagane jest urządzenie z dostępem do internetu, aktualna przeglądarka oraz aktywny adres e-mail. Przy konsultacji online potrzebne jest urządzenie umożliwiające połączenie audio i wideo. Zabronione jest przekazywanie treści bezprawnych lub zakłócających działanie strony.\n\n4. REZERWACJA I ZAWARCIE UMOWY\n\nKlient wybiera usługę, termin i formę wizyty, podaje wymagane dane, akceptuje Regulamin, zapoznaje się z Polityką prywatności i przechodzi do płatności. Umowa zostaje zawarta po prawidłowej płatności i otrzymaniu potwierdzenia na podany e-mail. Nieopłacona rezerwacja może zostać automatycznie anulowana po upływie czasu wskazanego podczas rezerwacji.\n\n5. CENY I PŁATNOŚCI\n\nCeny są podawane w złotych polskich. Płatności internetowe obsługuje Stripe. Dostępne metody zależą od operatora płatności. Usługodawca nie otrzymuje pełnych danych karty Klienta.\n\n6. REALIZACJA KONSULTACJI\n\nKonsultacja odbywa się w terminie i formie z potwierdzenia. Klient powinien stawić się punktualnie lub dołączyć do spotkania online. Konsultacja dietetyczna nie zastępuje diagnostyki lekarskiej ani leczenia prowadzonego przez lekarza.\n\n7. ZMIANA TERMINU, ANULOWANIE I NIEOBECNOŚĆ\n\nSamodzielne anulowanie lub przełożenie wizyty jest możliwe do terminu wskazanego podczas rezerwacji i w potwierdzeniu. Po jego upływie zmiana lub zwrot wymagają indywidualnego uzgodnienia. Nieobecność bez wcześniejszego odwołania może skutkować uznaniem usługi za niewykorzystaną. Anulowanie przez stronę nie uruchamia automatycznie zwrotu płatności.\n\n8. PRAWO ODSTĄPIENIA\n\nJeżeli przepisy przyznają Klientowi prawo odstąpienia od umowy na odległość, może on złożyć oświadczenie w ustawowym terminie. Gdy na wyraźne żądanie Klienta wykonanie rozpocznie się przed upływem tego terminu, Klient może być zobowiązany do zapłaty za wykonaną część. Po pełnym wykonaniu usługi, po spełnieniu warunków ustawowych, prawo odstąpienia może wygasnąć.\n\n9. REKLAMACJE\n\nReklamacje można przesyłać na {{EMAIL}}. Powinny zawierać dane pozwalające zidentyfikować rezerwację, opis problemu i oczekiwane rozwiązanie. Odpowiedź zostanie udzielona w terminie wymaganym przez przepisy.\n\n10. OPINIE\n\nOpinie z formularza są moderowane. Publikowane są tylko treści, na których udostępnienie autor wyraził zgodę. Publiczny formularz nie oznacza automatycznego powiązania opinii z konkretną rezerwacją. Usługodawca nie publikuje opinii fałszywych ani zamówionych.\n\n11. DANE OSOBOWE I COOKIES\n\nZasady przetwarzania danych opisuje Polityka prywatności. Informacje o technicznych plikach cookies zawiera Polityka cookies.\n\n12. POSTANOWIENIA KOŃCOWE\n\nRegulamin jest udostępniany nieodpłatnie w sposób pozwalający go zapisać i odtworzyć. Po potwierdzeniu płatnej rezerwacji Klient otrzymuje kopię zaakceptowanej wersji. Zmiany nie wpływają na umowy zawarte przed wejściem nowej wersji w życie."
PRIVACY_CONTENT = "POLITYKA PRYWATNOŚCI\n\n1. ADMINISTRATOR\n\nAdministratorem danych jest {{BUSINESS_NAME}}, prowadzona przez {{OWNER_NAME}}, adres: {{ADDRESS}}, NIP: {{TAX_ID}}.\nKontakt w sprawach danych: {{EMAIL}}, {{PHONE}}.\n\n2. ZAKRES DANYCH\n\nMożemy przetwarzać imię, nazwisko, e-mail, telefon, termin i rodzaj konsultacji, wiadomość organizacyjną, status i identyfikatory płatności, treść opinii, dane newsletterowe oraz techniczne logi serwera.\n\nNie wpisuj szczegółowych informacji o zdrowiu w wiadomości rezerwacyjnej. Ewentualne przyszłe formularze zdrowotne otrzymają osobną informację i zabezpieczenia.\n\n3. CELE I PODSTAWY\n\nDane rezerwacyjne służą działaniom przed zawarciem umowy, wykonaniu umowy, obsłudze płatności, kontaktowi, reklamacjom i ochronie roszczeń. Dane wymagane podatkowo i rachunkowo służą wykonaniu obowiązków prawnych.\n\nImię i e-mail newslettera są przetwarzane na podstawie dobrowolnej zgody. Opinie są przetwarzane na podstawie zgody na publikację i prawnie uzasadnionego interesu obejmującego prezentowanie doświadczeń klientów oraz ochronę przed nadużyciami. Logi techniczne służą bezpieczeństwu i diagnostyce.\n\n4. ODBIORCY\n\nDane mogą otrzymywać dostawcy hostingu, poczty, obsługi technicznej, księgowej i prawnej oraz Stripe w zakresie płatności. Przy przekazaniu danych poza EOG stosowane są wymagane zabezpieczenia.\n\n5. RETENCJA\n\nDane rezerwacyjne i rozliczeniowe są przechowywane przez realizację usługi, a następnie przez okresy wymagane podatkowo, rachunkowo i terminami roszczeń. Dane newsletterowe — do wycofania zgody lub zakończenia newslettera, z zachowaniem dowodu zgody. Opinie — do wycofania zgody, utraty celu lub skutecznego żądania usunięcia. Logi — przez okres potrzebny do bezpieczeństwa i diagnostyki.\n\n6. PRAWA\n\nMogą przysługiwać prawa dostępu, sprostowania, usunięcia, ograniczenia, przenoszenia, sprzeciwu i wycofania zgody. Wycofanie nie podważa wcześniejszego zgodnego przetwarzania. Skargę można wnieść do Prezesa UODO.\n\n7. DOBROWOLNOŚĆ\n\nDane rezerwacyjne są dobrowolne, lecz niezbędne do zawarcia i wykonania umowy. Newsletter i opinie są dobrowolne.\n\n8. AUTOMATYZACJA I BEZPIECZEŃSTWO\n\nAdministrator nie podejmuje decyzji prawnych wyłącznie automatycznie. Stripe może używać własnych mechanizmów antyfraudowych. Stosowane są odpowiednie zabezpieczenia, w tym HTTPS na produkcji, kontrola dostępu i kopie bezpieczeństwa."
COOKIES_CONTENT = "POLITYKA PLIKÓW COOKIES\n\n1. CZYM SĄ COOKIES\n\nCookies to niewielkie informacje zapisywane w przeglądarce lub odczytywane z urządzenia podczas korzystania ze strony.\n\n2. AKTUALNIE UŻYWANE MECHANIZMY\n\nStrona wykorzystuje wyłącznie mechanizmy techniczne potrzebne do bezpiecznego działania formularzy, rezerwacji i panelu administratora. Cookie CSRF chroni formularze przed nieuprawnionym wysłaniem. Cookie sesyjne może zachowywać stan sesji, szczególnie w panelu administratora. Zamknięcie komunikatu o cookies zapisujemy lokalnie w przeglądarce i nie używamy tego do śledzenia.\n\n3. DOSTAWCY ZEWNĘTRZNI\n\nPłatność odbywa się na stronie Stripe, który może stosować własne cookies. Interfejs Bootstrap jest pobierany z CDN jsDelivr; dostawca może otrzymać techniczne informacje połączenia, np. IP i dane przeglądarki.\n\n4. ZGODA\n\nNiezbędne mechanizmy mogą działać bez uprzedniej zgody. Strona nie uruchamia obecnie cookies analitycznych ani marketingowych. Jeśli takie narzędzia zostaną dodane, będą zablokowane do dobrowolnej zgody, z możliwością równie łatwego odrzucenia i późniejszej zmiany decyzji.\n\n5. USTAWIENIA PRZEGLĄDARKI\n\nCookies można usunąć lub zablokować w przeglądarce. Zablokowanie technicznych cookies może uniemożliwić wysłanie formularza, rezerwację lub logowanie.\n\n6. KONTAKT\n\nPytania można wysyłać na {{EMAIL}}."


def create_initial_legal_documents(apps, schema_editor):
    LegalDocument = apps.get_model("main", "LegalDocument")
    effective_from = datetime.date(2026, 9, 23)
    for document_type, title, content in (
        ("terms", "Regulamin świadczenia usług", TERMS_CONTENT),
        ("privacy", "Polityka prywatności", PRIVACY_CONTENT),
        ("cookies", "Polityka plików cookies", COOKIES_CONTENT),
    ):
        LegalDocument.objects.get_or_create(
            document_type=document_type,
            version="1.0",
            defaults={
                "title": title,
                "effective_from": effective_from,
                "content": content,
                "is_published": True,
            },
        )


def remove_initial_legal_documents(apps, schema_editor):
    apps.get_model("main", "LegalDocument").objects.filter(version="1.0").delete()


class Migration(migrations.Migration):

    dependencies = [("main", "0014_newsletter")]

    operations = [
        migrations.AddField(model_name="sitesettings", name="business_address", field=models.TextField(blank=True, verbose_name="Adres działalności")),
        migrations.AddField(model_name="sitesettings", name="business_name", field=models.CharField(blank=True, help_text="Nazwa używana w regulaminie i polityce prywatności.", max_length=220, verbose_name="Pełna nazwa działalności")),
        migrations.AddField(model_name="sitesettings", name="contact_email", field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail kontaktowy")),
        migrations.AddField(model_name="sitesettings", name="contact_phone", field=models.CharField(blank=True, max_length=40, verbose_name="Telefon kontaktowy")),
        migrations.AddField(model_name="sitesettings", name="owner_name", field=models.CharField(default="Monika Kulik", max_length=180, verbose_name="Imię i nazwisko właścicielki")),
        migrations.AddField(model_name="sitesettings", name="tax_id", field=models.CharField(blank=True, max_length=20, verbose_name="NIP")),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_type", models.CharField(choices=[("terms", "Regulamin świadczenia usług"), ("privacy", "Polityka prywatności"), ("cookies", "Polityka plików cookies")], max_length=20, verbose_name="Rodzaj dokumentu")),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                ("version", models.CharField(help_text="Np. 1.0 albo 2026-09-23.", max_length=30, verbose_name="Wersja")),
                ("effective_from", models.DateField(verbose_name="Obowiązuje od")),
                ("content", models.TextField(help_text="Możesz użyć znaczników: {{BUSINESS_NAME}}, {{OWNER_NAME}}, {{ADDRESS}}, {{TAX_ID}}, {{EMAIL}}, {{PHONE}}.", verbose_name="Treść dokumentu")),
                ("is_published", models.BooleanField(default=False, help_text="Tylko opublikowane dokumenty są widoczne na stronie.", verbose_name="Opublikowany")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Zaktualizowano")),
            ],
            options={"verbose_name": "Dokument prawny", "verbose_name_plural": "Dokumenty prawne", "ordering": ["document_type", "-effective_from", "-pk"]},
        ),
        migrations.AddConstraint(model_name="legaldocument", constraint=models.UniqueConstraint(fields=("document_type", "version"), name="unique_legal_document_version")),
        migrations.RunPython(create_initial_legal_documents, remove_initial_legal_documents),
    ]
