# Generated by Django 6.0.7 on 2026-09-23

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def populate_newsletter_tokens(apps, schema_editor):
    Subscriber = apps.get_model("main", "NewsletterSubscriber")
    for subscriber in Subscriber.objects.all().iterator():
        subscriber.confirmation_token = uuid.uuid4()
        subscriber.unsubscribe_token = uuid.uuid4()
        if subscriber.consent_confirmed and subscriber.is_active:
            subscriber.confirmed_at = subscriber.consented_at or timezone.now()
        subscriber.save(
            update_fields=[
                "confirmation_token",
                "unsubscribe_token",
                "confirmed_at",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_legal_documents_and_business_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="confirmation_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Wysłano prośbę o potwierdzenie",
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Adres potwierdzony",
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="confirmation_token",
            field=models.UUIDField(
                editable=False,
                null=True,
                verbose_name="Token potwierdzenia adresu",
            ),
        ),
        migrations.AddField(
            model_name="newslettersubscriber",
            name="unsubscribe_token",
            field=models.UUIDField(
                editable=False,
                null=True,
                verbose_name="Token rezygnacji",
            ),
        ),
        migrations.RunPython(
            populate_newsletter_tokens,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="confirmation_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Token potwierdzenia adresu",
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="unsubscribe_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Token rezygnacji",
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Wiadomości otrzymują tylko osoby z potwierdzonym adresem."
                ),
                verbose_name="Aktywny zapis",
            ),
        ),
        migrations.CreateModel(
            name="NewsletterCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Widoczna tylko w panelu administratora.",
                        max_length=200,
                        verbose_name="Nazwa robocza kampanii",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=200,
                        verbose_name="Temat wiadomości",
                    ),
                ),
                (
                    "preheader",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Krótki tekst widoczny obok tematu w skrzynce "
                            "odbiorczej."
                        ),
                        max_length=250,
                        verbose_name="Tekst podglądu",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        max_length=250,
                        verbose_name="Nagłówek wiadomości",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text=(
                            "Zwykły tekst. Nowe akapity zachowają się "
                            "w wiadomości e-mail."
                        ),
                        verbose_name="Treść wiadomości",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="newsletter/campaigns/",
                        verbose_name="Grafika",
                    ),
                ),
                (
                    "button_label",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Tekst przycisku",
                    ),
                ),
                (
                    "button_url",
                    models.URLField(
                        blank=True,
                        verbose_name="Adres przycisku",
                    ),
                ),
                (
                    "test_recipient_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Adres do wysyłki testowej",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Wersja robocza"),
                            ("ready", "Gotowa do wysyłki"),
                            ("sending", "Wysyłanie"),
                            ("sent", "Wysłana"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text=(
                            "Wymaga cyklicznego uruchamiania komendy "
                            "wysyłającej na serwerze."
                        ),
                        null=True,
                        verbose_name="Planowana wysyłka",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Wysłano",
                    ),
                ),
                (
                    "recipient_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="Liczba odbiorców",
                    ),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="Liczba błędów",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Utworzono",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Zaktualizowano",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kampania newsletterowa",
                "verbose_name_plural": "Kampanie newsletterowe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscriber_email",
                    models.EmailField(
                        max_length=254,
                        verbose_name="Adres odbiorcy w chwili wysyłki",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje"),
                            ("sent", "Wysłana"),
                            ("failed", "Błąd"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Wysłano",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        verbose_name="Opis błędu",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Utworzono",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Zaktualizowano",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="main.newslettercampaign",
                        verbose_name="Kampania",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="main.newslettersubscriber",
                        verbose_name="Odbiorca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wysyłka newslettera",
                "verbose_name_plural": "Historia wysyłek newslettera",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="newsletterdelivery",
            constraint=models.UniqueConstraint(
                fields=("campaign", "subscriber"),
                name="unique_newsletter_delivery",
            ),
        ),
    ]
