# Generated by Django 6.0.7 on 2026-09-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_newsletter_campaigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Adres wyświetlany pacjentom na stronie Kontakt. Może być inny niż adres działalności używany w dokumentach prawnych.', verbose_name='Adres gabinetu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_description',
            field=models.TextField(default='Masz pytanie dotyczące konsultacji lub nie wiesz, którą usługę wybrać? Skontaktuj się ze mną w najwygodniejszy dla Ciebie sposób.', verbose_name='Opis strony Kontakt'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_heading',
            field=models.CharField(default='Porozmawiajmy o Twoim zdrowiu', max_length=180, verbose_name='Nagłówek strony Kontakt'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_hours',
            field=models.TextField(blank=True, help_text='Np. poniedziałek–piątek, 9:00–17:00.', verbose_name='Godziny kontaktu'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True, verbose_name='Link do Google Maps'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
    ]
