# Generated by Django 6.0.7 on 2026-09-27 15:59

import django.core.validators
import main.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sitesettings_contact_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQuestionnaireDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ankieta personalna pacjenta', max_length=180, verbose_name='Nazwa ankiety')),
                ('file', models.FileField(help_text='Plik jest przechowywany poza publicznym katalogiem mediów.', storage=main.storage.PrivateDocumentStorage(), upload_to='questionnaires/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Plik PDF')),
                ('is_active', models.BooleanField(default=True, help_text='Tylko aktywna wersja jest udostępniana w podglądzie.', verbose_name='Aktywna wersja')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zmieniono')),
            ],
            options={
                'verbose_name': 'Ankieta pacjenta',
                'verbose_name_plural': 'Ankiety pacjenta',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
